### ISSUE TITLE
ES6 imports do not work in browser

### ISSUE THREAD

**Issue by TzviPM** [h-sifat/flexible-tree-printer#1]
When trying to import the compiled UMD from unpkg, I receive the following error:

```
TypeError: Cannot set properties of undefined (setting 'flexible_tree_printer')
```

Repro steps:

1. Opena. browser tab
2. open devtools console
3. run `const pkg = await import("https://www.unpkg.com/flexible-tree-printer");`

Browser: Chrome Version 123.0.6312.87 (Official Build) (arm64)
Operating System: MacOS Sonoma 14.4.1 (23E224)
UNPKG URL: https://www.unpkg.com/flexible-tree-printer@1.0.2/dist/index.js

**Comment by h-sifat** [comment]
Hi, there. Thanks for mentioning the issue. I'll try to look into it soon.

**Comment by h-sifat** [comment]
Closing after reviewing and merging your pull request. Thank you.
